name: Docker Image CI  

on:
  push:
    branches: [main]
  pull_request:
     branches: [main]
   
jobs:
  push_to_registries:
   name: push Docker image to multiple registries
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build and publish head Docker Image     
        uses: VaultVulp/gp-docker-action@1.1.1.7
        with:
         github.token: ${{secrets.TOKEN}}
         image.name: myjavaapp
         image-tags: head
        
    
